version: '3.4'

services:
  xerodemo.identity.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Xero__ClientId=9352203A44934F10AB1AE6C4EDFE67A2
      - Xero__ClientSecret=Vh18QLA65yJXDsew76G4Wg8a1V44ypw73-FReC_R0ntisHam
    ports:
      - "64096:80"
      - "64097:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - "./Components/:/components"

  xerodemo.planner.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "64098:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xerodemo.tenent.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "64099:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - "./Components/:/components"

  xerodemo.payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "64095:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xerodemo.web.planner:
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=false
    ports:
      - "64091:80"

