version: '3.4'

services:
  xerodemo.identity.web:
    image: ${DOCKER_REGISTRY-}xerodemoidentityweb
    build:
      context: .
      dockerfile: Identity/XeroDemo.Identity.Web/Dockerfile
    depends_on:
      - redis
      - placement
    networks:
      - xero-network

  xerodemo.identity.web-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
     "-app-id", "xerodemoidentityweb",
     "-app-port", "443",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    depends_on:
      - xerodemo.identity.web
    network_mode: "service:xerodemo.identity.web"
    volumes:
        - "./Components/:/components"

  xerodemo.planner.api:
    image: ${DOCKER_REGISTRY-}xerodemoplannerapi
    build:
      context: .
      dockerfile: Planner/XeroDemo.Planner.Api/Dockerfile

  xerodemo.tenent.api:
    image: ${DOCKER_REGISTRY-}xerodemotenentapi
    build:
      context: .
      dockerfile: TenentService/XeroDemo.TenentService.Api/Dockerfile
    depends_on:
      - redis
      - placement
    networks:
      - xero-network

  xerodemo.tenent.api-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
     "-app-id", "xerodemotenentapi",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    depends_on:
      - xerodemo.tenent.api
    network_mode: "service:xerodemo.tenent.api"
    volumes:
        - "./Components/:/components"

  xerodemo.payment.api:
    image: ${DOCKER_REGISTRY-}xerodemopaymentapi
    build:
      context: .
      dockerfile: Payment/XeroDemo.Payment.Api/Dockerfile

  xerodemo.web.planner:
    image: ${DOCKER_REGISTRY-}xerodemowebplanner
    build:
      context: .
      dockerfile: Web/XeroDemo.Web.Planner/Dockerfile

 ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - xero-network
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - xero-network
networks:
    xero-network:
