version: '3.4'

services:
  xerodemo.identity.web:
    image: ${DOCKER_REGISTRY-}xerodemoidentityweb
    build:
      context: .
      dockerfile: Identity/XeroDemo.Identity.Web/Dockerfile

  xerodemo.identity.web-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "xerodemo.identity.web", "-app-port", "443" ]
    depends_on:
      - xerodemo.identity.web
    network_mode: "service:xerodemo.identity.web"

  xerodemo.planner.api:
    image: ${DOCKER_REGISTRY-}xerodemoplannerapi
    build:
      context: .
      dockerfile: Planner/XeroDemo.Planner.Api/Dockerfile

  xerodemo.tenent.api:
    image: ${DOCKER_REGISTRY-}xerodemotenentapi
    build:
      context: .
      dockerfile: TenentService/XeroDemo.TenentService.Api/Dockerfile

  xerodemo.tenent.api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "xerodemo.tenent.api", "-app-port", "80" ]
    depends_on:
      - xerodemo.tenent.api
    network_mode: "service:xerodemo.tenent.api"

  xerodemo.payment.api:
    image: ${DOCKER_REGISTRY-}xerodemopaymentapi
    build:
      context: .
      dockerfile: Payment/XeroDemo.Payment.Api/Dockerfile

  xerodemo.web.planner:
    image: ${DOCKER_REGISTRY-}xerodemowebplanner
    build:
      context: .
      dockerfile: Web/XeroDemo.Web.Planner/Dockerfile
