version: '3.4'

services:
  xerodemo.identity.web:
    image: ${DOCKER_REGISTRY-}xerodemoidentityweb
    build:
      context: .
      dockerfile: Identity/XeroDemo.Identity.Web/Dockerfile

  xerodemo.web.planner:
    image: ${DOCKER_REGISTRY-}xerodemowebplanner
    build:
      context: .
      dockerfile: Web/XeroDemo.Web.Planner/Dockerfile

