version: '3.4'

services:
  xerodemo.identity.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - Xero__ClientId=9352203A44934F10AB1AE6C4EDFE67A2
      - Xero__ClientSecret=Vh18QLA65yJXDsew76G4Wg8a1V44ypw73-FReC_R0ntisHam
      - ConnectionStrings__DefaultConnection=Server=idenitityDb;Database=Identity02;User=sa;Password=Your_password123;
    ports:
      - "64096:80"
      - "64097:443"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https:ro

  xerodemo.planner.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "64098:80"

  xerodemo.tenent.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "64099:80"

  xerodemo.payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "64095:80"

  xerodemo.planner.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "64094:80"

  idenitityDb:
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    networks:
        - xero-network

